In [7]:
# Load libraries
from pandas import read_csv
from pandas.plotting import scatter_matrix
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [111]:
# Load dataset
url = "https://raw.githubusercontent.com/avhadutgadhave/MLOP-s-POC-AWS/master/iris.csv"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'clas']
dataset = read_csv(url, names=names)

In [112]:

# shape
print(dataset.shape)

(150, 5)


In [378]:

# head
print(dataset.head(50))

    sepal-length  sepal-width  petal-length  petal-width   class
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8         

In [177]:

# descriptions
print(dataset.describe())

       sepal-length  sepal-width  petal-length  petal-width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


In [379]:
array = dataset.values 

In [380]:
X = array[:,0:4] 
Y = array[:,4] 
scaler = MinMaxScaler(feature_range=(0, 2)) 
rescaledX = scaler.fit_transform(X) 

In [381]:
numpy.set_printoptions(precision=3) 
print(rescaledX[0:150,:]) 

[[0.444 1.25  0.136 0.083]
 [0.333 0.833 0.136 0.083]
 [0.222 1.    0.102 0.083]
 [0.167 0.917 0.169 0.083]
 [0.389 1.333 0.136 0.083]
 [0.611 1.583 0.237 0.25 ]
 [0.167 1.167 0.136 0.167]
 [0.389 1.167 0.169 0.083]
 [0.056 0.75  0.136 0.083]
 [0.333 0.917 0.169 0.   ]
 [0.611 1.417 0.169 0.083]
 [0.278 1.167 0.203 0.083]
 [0.278 0.833 0.136 0.   ]
 [0.    0.833 0.034 0.   ]
 [0.833 1.667 0.068 0.083]
 [0.778 2.    0.169 0.25 ]
 [0.611 1.583 0.102 0.25 ]
 [0.444 1.25  0.136 0.167]
 [0.778 1.5   0.237 0.167]
 [0.444 1.5   0.169 0.167]
 [0.611 1.167 0.237 0.083]
 [0.444 1.417 0.169 0.25 ]
 [0.167 1.333 0.    0.083]
 [0.444 1.083 0.237 0.333]
 [0.278 1.167 0.305 0.083]
 [0.389 0.833 0.203 0.083]
 [0.389 1.167 0.203 0.25 ]
 [0.5   1.25  0.169 0.083]
 [0.5   1.167 0.136 0.083]
 [0.222 1.    0.203 0.083]
 [0.278 0.917 0.203 0.083]
 [0.611 1.167 0.169 0.25 ]
 [0.5   1.75  0.169 0.   ]
 [0.667 1.833 0.136 0.083]
 [0.333 0.917 0.169 0.   ]
 [0.389 1.    0.068 0.083]
 [0.667 1.25  0.102 0.083]
 

In [310]:
from sklearn.preprocessing import Binarizer 

In [298]:
binarizer = Binarizer(threshold=0.0).fit(scaler.transform(X)) 


In [300]:
binaryX = binarizer.transform(scaler.transform(X)) 

In [286]:
numpy.set_printoptions(precision=3 

In [312]:
print(binaryX[0:150,:]) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [0. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1.

In [313]:
from sklearn.preprocessing import StandardScaler

In [317]:
scaler = StandardScaler().fit(X) 
rescaledX = scaler.transform(X) 

In [371]:
numpy.set_printoptions(precision=3) 
#print(rescaledX[0:50,])
print(rescaledX[0:50,])
#print(rescaledX[100:150,])



[[-0.901  1.032 -1.341 -1.313]
 [-1.143 -0.125 -1.341 -1.313]
 [-1.385  0.338 -1.398 -1.313]
 [-1.507  0.106 -1.284 -1.313]
 [-1.022  1.263 -1.341 -1.313]
 [-0.537  1.958 -1.171 -1.05 ]
 [-1.507  0.801 -1.341 -1.182]
 [-1.022  0.801 -1.284 -1.313]
 [-1.749 -0.356 -1.341 -1.313]
 [-1.143  0.106 -1.284 -1.444]
 [-0.537  1.495 -1.284 -1.313]
 [-1.264  0.801 -1.228 -1.313]
 [-1.264 -0.125 -1.341 -1.444]
 [-1.87  -0.125 -1.512 -1.444]
 [-0.053  2.189 -1.455 -1.313]
 [-0.174  3.115 -1.284 -1.05 ]
 [-0.537  1.958 -1.398 -1.05 ]
 [-0.901  1.032 -1.341 -1.182]
 [-0.174  1.726 -1.171 -1.182]
 [-0.901  1.726 -1.284 -1.182]
 [-0.537  0.801 -1.171 -1.313]
 [-0.901  1.495 -1.284 -1.05 ]
 [-1.507  1.263 -1.569 -1.313]
 [-0.901  0.569 -1.171 -0.919]
 [-1.264  0.801 -1.057 -1.313]
 [-1.022 -0.125 -1.228 -1.313]
 [-1.022  0.801 -1.228 -1.05 ]
 [-0.78   1.032 -1.284 -1.313]
 [-0.78   0.801 -1.341 -1.313]
 [-1.385  0.338 -1.228 -1.313]
 [-1.264  0.106 -1.228 -1.313]
 [-0.537  0.801 -1.284 -1.05 ]
 [-0.78 

In [368]:
from sklearn.model_selection import train_test_split

In [372]:
setosa=rescaledX[0:50,]

In [373]:
versicolor=rescaledX[50:100,]

In [374]:
virginica=rescaledX[100:150,]

In [377]:
print(virginica)

[[ 0.553  0.569  1.275  1.711]
 [-0.053 -0.819  0.763  0.922]
 [ 1.523 -0.125  1.218  1.185]
 [ 0.553 -0.356  1.047  0.791]
 [ 0.796 -0.125  1.161  1.316]
 [ 2.129 -0.125  1.616  1.185]
 [-1.143 -1.282  0.422  0.659]
 [ 1.765 -0.356  1.445  0.791]
 [ 1.038 -1.282  1.161  0.791]
 [ 1.644  1.263  1.331  1.711]
 [ 0.796  0.338  0.763  1.054]
 [ 0.675 -0.819  0.876  0.922]
 [ 1.159 -0.125  0.99   1.185]
 [-0.174 -1.282  0.706  1.054]
 [-0.053 -0.588  0.763  1.579]
 [ 0.675  0.338  0.876  1.448]
 [ 0.796 -0.125  0.99   0.791]
 [ 2.25   1.726  1.673  1.316]
 [ 2.25  -1.051  1.786  1.448]
 [ 0.19  -1.976  0.706  0.396]
 [ 1.28   0.338  1.104  1.448]
 [-0.295 -0.588  0.649  1.054]
 [ 2.25  -0.588  1.673  1.054]
 [ 0.553 -0.819  0.649  0.791]
 [ 1.038  0.569  1.104  1.185]
 [ 1.644  0.338  1.275  0.791]
 [ 0.432 -0.588  0.592  0.791]
 [ 0.311 -0.125  0.649  0.791]
 [ 0.675 -0.588  1.047  1.185]
 [ 1.644 -0.125  1.161  0.528]
 [ 1.886 -0.588  1.331  0.922]
 [ 2.492  1.726  1.502  1.054]
 [ 0.675