In [6]:
# Python version
import sys
print('Python: {}'.format(sys.version))
# scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
# numpy
import numpy
print('numpy: {}'.format(numpy.__version__))
# matplotlib
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
# pandas
import pandas
print('pandas: {}'.format(pandas.__version__))
# scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))

Python: 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
scipy: 1.3.3
numpy: 1.17.4
matplotlib: 3.1.2
pandas: 0.25.3
sklearn: 0.21.3


In [7]:
# Load libraries
from pandas import read_csv
from pandas.plotting import scatter_matrix
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [31]:
# Load dataset
url = "https://raw.githubusercontent.com/avhadutgadhave/MLOP-s-POC-AWS/master/iris.csv"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = read_csv(url, names=names)

In [32]:

# shape
print(dataset.shape)

(150, 5)


In [33]:

# head
print(dataset.head(10))

   sepal-length  sepal-width  petal-length  petal-width   class
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa


In [34]:

# descriptions
print(dataset.describe())

       sepal-length  sepal-width  petal-length  petal-width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


In [57]:
array = dataset.values 

In [60]:
X = array[:,0:5] 


In [62]:
Y = array[:3] 


In [70]:
from sklearn.preprocessing import StandardScaler

In [73]:
StandardScaler(copy=True, with_mean=True, with_std=True)
scaler = StandardScaler()

In [76]:
print(scaler.fit(array))

StandardScaler(copy=True, with_mean=True, with_std=True)


In [77]:
print(scaler.mean_)

[69.44  71.807 83.16 ]


In [78]:
print(scaler.transform(array))

[[-1.072  0.402 -0.328]
 [-0.638 -1.522 -1.563]
 [ 0.786 -0.858  1.145]
 [-1.555  1.177 -0.805]
 [ 0.617 -0.792  1.318]
 [-1.338  0.911 -1.065]
 [ 0.762 -0.637  1.21 ]
 [-1.217 -0.792 -0.762]
 [-1.579 -1.234  1.426]
 [-0.252 -1.323 -0.913]
 [ 0.665 -0.593 -0.935]
 [-0.517  1.154 -1.347]
 [-0.131  0.712 -0.545]
 [-1.483  1.265  0.711]
 [ 1.268 -0.261  0.906]
 [ 0.737 -0.571  0.906]
 [-0.445  0.734 -0.22 ]
 [ 1.461 -1.234  1.275]
 [-1.579  1.132  1.015]
 [-0.735 -0.482  0.495]
 [ 1.051 -0.283  0.863]
 [ 0.569  0.115  0.192]
 [ 0.713 -0.328 -1.39 ]
 [ 0.038 -0.659  0.321]
 [ 0.472 -0.681 -1.043]
 [-0.686 -0.372  0.516]
 [ 1.775 -1.411  0.451]
 [-0.276 -0.018 -0.567]
 [-1.579  1.044 -1.087]
 [-0.397  0.026 -0.783]
 [ 1.606 -1.212  1.361]
 [ 1.027  1.287 -0.718]
 [-0.59   1.663 -0.372]
 [ 0.303 -1.013  0.971]
 [ 1.293  0.933  0.798]
 [-0.759 -1.367 -0.068]
 [-1.459 -0.637  0.083]
 [-1.459 -0.062 -1.585]
 [-1.627  0.69   1.123]
 [-1.362 -0.283 -1.802]
 [-1.362 -0.018  1.058]
 [ 1.486 -0.328 

In [79]:
from sklearn.preprocessing import Binarizer 

In [80]:
binarizer = Binarizer(threshold=0.0).fit(scaler.transform(array)) 


In [81]:
binaryX = binarizer.transform(scaler.transform(array)) 

In [82]:
numpy.set_printoptions(precision=3) 

In [84]:
print(binaryX[0:150,:]) 

[[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 0. 1.]
 [1. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 1.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 1. 1.]
 [0. 0. 0.]
 [0. 0. 1.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 0.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 0. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [1. 0. 1.]
 [0. 0. 0.]
 [0. 1. 1.]
 [1. 1. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 1. 1.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0.

In [85]:
from sklearn.preprocessing import StandardScaler

In [86]:
scaler = StandardScaler().fit(binaryX[0:150,:]) 
rescaledX = scaler.transform(binaryX[0:150,:]) 

In [87]:
numpy.set_printoptions(precision=3) 
print(rescaledX[0:150,:]) 

[[-0.935  1.041 -1.013]
 [-0.935 -0.961 -1.013]
 [ 1.069 -0.961  0.987]
 [-0.935  1.041 -1.013]
 [ 1.069 -0.961  0.987]
 [-0.935  1.041 -1.013]
 [ 1.069 -0.961  0.987]
 [-0.935 -0.961 -1.013]
 [-0.935 -0.961  0.987]
 [-0.935 -0.961 -1.013]
 [ 1.069 -0.961 -1.013]
 [-0.935  1.041 -1.013]
 [-0.935  1.041 -1.013]
 [-0.935  1.041  0.987]
 [ 1.069 -0.961  0.987]
 [ 1.069 -0.961  0.987]
 [-0.935  1.041 -1.013]
 [ 1.069 -0.961  0.987]
 [-0.935  1.041  0.987]
 [-0.935 -0.961  0.987]
 [ 1.069 -0.961  0.987]
 [ 1.069  1.041  0.987]
 [ 1.069 -0.961 -1.013]
 [ 1.069 -0.961  0.987]
 [ 1.069 -0.961 -1.013]
 [-0.935 -0.961  0.987]
 [ 1.069 -0.961  0.987]
 [-0.935 -0.961 -1.013]
 [-0.935  1.041 -1.013]
 [-0.935  1.041 -1.013]
 [ 1.069 -0.961  0.987]
 [ 1.069  1.041 -1.013]
 [-0.935  1.041 -1.013]
 [ 1.069 -0.961  0.987]
 [ 1.069  1.041  0.987]
 [-0.935 -0.961 -1.013]
 [-0.935 -0.961  0.987]
 [-0.935 -0.961 -1.013]
 [-0.935  1.041  0.987]
 [-0.935 -0.961 -1.013]
 [-0.935 -0.961  0.987]
 [ 1.069 -0.961 